/* Regenerate src/game/manifest.ts.
   Searching for a winnable shuffle costs up to a few seconds per level, which
   is far too slow to do while a player waits. The search runs here instead and
   the answer ships as a table, so starting a level is instant.
   Run with: npm run manifest */
import { writeFileSync } from 'node:fs';
import { TOTAL_LEVELS } from '../game/campaign';
import { dealSolvable } from '../game/level';

const rows: string[] = [];
let unverified = 0;
const t0 = Date.now();

for (let level = 1; level <= TOTAL_LEVELS; level++) {
  // level 5 is the reference deal from the recording and keeps its own seed
  const d = dealSolvable(level, level === 5 ? 'recording' : `level-${level}`);
  if (!d.verified) unverified++;
  const s = d.state;
  const cats = new Set(
    [...s.columns.flatMap((c) => c.cards), ...s.stock]
      .filter((c) => c.kind === 'category').map((c) => c.value)
  ).size;
  rows.push(`  ${level}: { seed: ${JSON.stringify(s.seedName)}, moves: ${s.movesMax}, sets: ${cats} },`);
  if (level % 100 === 0) console.log(`  ...${level}`);
}

const file = `/* GENERATED by \`npm run manifest\` -- do not edit by hand.

   Each level was dealt, played through by the solver, and the first shuffle it
   could finish was kept along with the move budget that shuffle needs. Every
   entry here is therefore a board that is known to be completable. */

export interface ManifestEntry { seed: string; moves: number; sets: number }

export const LEVEL_MANIFEST: Record<number, ManifestEntry> = {
${rows.join('\n')}
};
`;
writeFileSync('src/game/manifest.ts', file);
console.log(`wrote ${rows.length} levels in ${((Date.now() - t0) / 1000).toFixed(1)}s, unverified: ${unverified}`);

